### ISSUE TITLE
have error

### ISSUE THREAD

**Issue by vTNT** [ybalt/ansible-tower#1]
dockerfile should be change this line : "ADD licence /etc/tower/license"  to "ADD license /etc/tower/license"

**Comment by ybalt** [comment]
Fixed in latest version as well as certificate mapping and ServerName in Apache config.
Thanks!

**Comment by vTNT** [comment]
the README.md should be change this line : ' ~/certs/domain.license ' to '  ~/certs/license ' ,  or change the docker-entrypoint.sh:  ' if [[ -a /certs/license ]]; then ' -a /certs/domain.license  '   and 'cp -r /certs/license /etc/tower/license'  to 'cp -r /certs/domain.license /etc/tower/license'

**Comment by ybalt** [comment]
Yea, it's a typo, thanks

**Comment by vTNT** [comment]
docker-entrypoint.sh should be change this line : ' chown awx:awx /etc//tower/tower.cert ' to ' chown awx:awx /etc/tower/tower.cert '

**Comment by ybalt** [comment]
vTNT,
Not a critical typo, but anyway - thanks. Do you tried run in by yourself?
